version: "3"
services:
  nexus:
    image: sonatype/nexus3
    restart: always
    volumes:
      - "nexus-data:/nexus-data"
    # ports:
    #   - "8081:8081"
    #   - "8085:8085"
    network_mode: host
volumes:
  nexus-data: {}
