---
- name: Create a user, add sudo access, and copy SSH key from file
  hosts: all
  become: yes
  vars:
    username: "support"
  tasks:
  - name: Set up multiple authorized keys
    ansible.posix.authorized_key:
      user: "{{ username }}"
      state: present
      key: '{{ item }}'
    with_file:
      - /home/ubuntu/.ssh/id_rsa.pub
 #     - public_keys/doe-john
