---
- name: Create a user, add sudo access, and copy SSH key from file
  hosts: all
  become: yes
  vars:
    username: "user"
    password: "{{ 'Strongpassword' | password_hash('sha512') }}"
    ssh_pub_key_file: "/home/ubuntu/.ssh/id_rsa.pub"  # Adjust this path to your actual key file
  tasks:
    - name: Create a new user
      user:
        name: "{{ username }}"
        password: "{{ password }}"
        shell: /bin/bash
        state: present

    - name: Create sudoers file for the user
      copy:
        content: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
        dest: "/etc/sudoers.d/{{ username }}"
        owner: root
        group: root
        mode: '0440'
        validate: 'visudo -cf %s'

