---
- name: Ensure PostgreSQL users are present.
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password | default(omit) }}"
  with_items: "{{ postgresql_users }}"
    #no_log: "{{ postgres_users_no_log }}"
  become: true
  become_user: "postgres"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
