- name: Run using a project directory
  hosts: nexus
  gather_facts: false
  become: true
  tasks:
    - name: copy Docker Compose files
      copy:
        src: ../files/{{ item }}
        dest: /opt/{{ item }}
      loop:
      - runner-docker-compose.yml

    - name: deploy Docker Compose stack
      community.docker.docker_compose_v2:
        project_src: /opt/
        files:
        - runner-docker-compose.yml
      register: output

    - name: Show results
      ansible.builtin.debug:
        var: output

    - name: Run a simple command (command)
      community.docker.docker_container_exec:
        container: gitlab-runner1
        command: gitlab-runner register --non-interactive \
           --registration-token <token> \
           --locked=false \
           --description docker-stable \
           --url https://git.example.kz \
           --executor docker \
           --docker-image alpine \
           --docker-volumes "/var/run/docker.sock:/var/run/docker.sock"
 #       chdir: /nexus-data
      register: result

    - name: Print stdout
      ansible.builtin.debug:
        var: result.stdout

